#!/bin/bash
# devc host-side init (devcontainer "initializeCommand").
#
# Runs on the HOST, before the container is created — the only lifecycle hook that
# does. Its job: ensure the bind-mount sources exist, because `--mount type=bind`
# errors on a missing source rather than creating it. So a clone of this
# .devcontainer/ comes up cleanly even for someone who has never run `devc` (the
# `devc` CLI otherwise guarantees the ~/.claude one itself via ensureClaudeSeedDir).
#
# Idempotent; also runs on subsequent starts.
set -e
mkdir -p "$HOME/.config/devc/.claude"

# User-level shell customization: every *.sh here is sourced by every interactive container
# shell (see the USER_SHELL_DIR layer in scripts/bashrc-additions.sh). Created empty so the
# mount source exists; devc never writes into it.
mkdir -p "$HOME/.config/devc/shell"

# Git identity for the container. ~/.gitconfig is container-local and wiped on every
# rebuild, so the container has no idea who you are. Rather than bind the whole host
# ~/.gitconfig — which would drag in host-absolute paths, credential helpers, and
# signing config that don't work in here — extract an explicit allowlist. Only the
# keys below cross the boundary.
#
# Always written (even when the host has no identity configured) so the bind-mount source
# exists. `git config --file` does the writing rather than `echo`, so a value containing
# `#`, `;`, `"` or `\` is quoted the way git's own parser expects to read it back.
identity="$HOME/.config/devc/gitconfig-identity"
printf '%s\n' "# Generated by devc initialize-command.sh — do not edit." > "$identity"
name="$(git config --get user.name || true)"
email="$(git config --get user.email || true)"
[ -n "$name" ] && git config --file "$identity" user.name "$name"
[ -n "$email" ] && git config --file "$identity" user.email "$email"

# devc:bridge-placeholder (start)
# devc-bridge mount sources. The mounts themselves are declared by the `devc-bridge` Feature
# (see the `features` block in devcontainer.json), which — like every Feature — has no
# host-side hook and so cannot create them. devc does have one, which is why this block stays
# here: it is what keeps the bridge inert rather than fatal for devc users who never installed
# it. A standalone project using only the Feature gets no such courtesy and fails the create
# with Docker's "bind source path does not exist" — that difference is deliberate.
#
# Created empty; the bridge's own installer (or `deno task build:client`) fills the client
# dir in.
mkdir -p "$HOME/.config/devc-bridge/run" "$HOME/.config/devc-bridge/client"

# Placeholder so the PATH symlink the Feature's install.sh makes always resolves; without it
# bash reports a bare "No such file or directory". Created ONLY when absent —
# this script runs before every `up`, and an unconditional write would clobber the real
# client the bridge installed there. Exit 127 is the shell's own "command not found"
# convention; the message is diagnostic rather than instructional, since a failed
# cross-compile leaves the placeholder in place too.
placeholder="$HOME/.config/devc-bridge/client/devc-bridge"
if [ ! -e "$placeholder" ]; then
  cat > "$placeholder" <<'PLACEHOLDER'
#!/bin/sh
echo "devc-bridge: no client binary — host bridge not started, or its client build failed" >&2
exit 127
PLACEHOLDER
  chmod 0755 "$placeholder"
fi
# devc:bridge-placeholder (end)

# Explicit, because the git-identity tests above are the last thing that can set $?: an unset
# name or email leaves the final `[ -n ... ]` failing, and a non-zero initializeCommand aborts
# container creation. A host with no git identity is a warning (from scripts/git-setup.sh),
# not a failure.
exit 0
